name: Test all  platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  build:
    name: ${{ matrix.command }} on  ${{ matrix.platform }} (xcode ${{ matrix.xcode }}, ${{ matrix.macos }})
    runs-on: macos-latest 
    strategy:
      fail-fast: false
      matrix:
        xcode: ['14.3.1']
        macos: ['macos-latest']
        scheme: ['TeslaKit']
        command: ['test']
        platform: ['iOS', 'mac-catalyst']
        exclude:
          - macos: 'macos-latest'
            xcode: '14.3.1'
    steps:
    - name: Switch xcode to 14.3.1
      uses: actions/checkout@v3
      with:
        xcode-version: '14.3.1'
    - name: Double-check macOS version macos-latest
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - name: Show eligible build destinations for TeslaKit
      run: xcodebuild -showdestinations -scheme 'TeslaKit'
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: 'iOS'
        scheme: 'TeslaKit'
        action: 'test'
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
